# Generated by Django 5.0.6 on 2024-05-23 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prerequisites', models.CharField(blank=True, max_length=200)),
                ('benefits', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('script', models.CharField(blank=True, max_length=50)),
                ('typical_settings', models.CharField(blank=True, max_length=200)),
                ('special_characteristics', models.TextField(blank=True)),
                ('translation_difficulty', models.CharField(blank=True, max_length=50)),
                ('magical_properties', models.TextField(blank=True)),
                ('learning_methods', models.TextField(blank=True)),
                ('famous_texts', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('არცერთი', 'არცერთი'), ('უბრალო', 'უბრალო'), ('უჩვეულო', 'უჩვეულო'), ('იშვიათი', 'იშვიათი'), ('ძალიან იშვიათი', 'ძალიან იშვიათი'), ('ლეგენდარული', 'ლეგენდარული'), ('არტეფაქტი', 'არტეფაქტი')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingThrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ability_score_increases', models.TextField()),
                ('size', models.CharField(max_length=20)),
                ('speed', models.IntegerField()),
                ('traits', models.TextField()),
                ('racial_features', models.TextField(blank=True)),
                ('languages', models.ManyToManyField(blank=True, to='myapp.language')),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='myapp.race'),
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('armor_class', models.IntegerField()),
                ('strength_requirement', models.IntegerField()),
                ('stealth_disadvantage', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost', models.CharField(max_length=20)),
                ('weight_class', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy'), ('None', 'None')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rarity')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ability_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.abilityscore')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('hit_die', models.IntegerField()),
                ('powers_description', models.TextField(blank=True)),
                ('armor_proficiencies', models.ManyToManyField(to='myapp.armor')),
                ('spellcasting_ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spellcasting_ability_for', to='myapp.abilityscore')),
                ('saving_throw_proficiencies', models.ManyToManyField(limit_choices_to={'id__lte': 2}, to='myapp.savingthrow')),
                ('skill_proficiencies', models.ManyToManyField(to='myapp.skill')),
                ('tool_proficiencies', models.ManyToManyField(to='myapp.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('school', models.CharField(max_length=50)),
                ('casting_time', models.CharField(max_length=50)),
                ('range', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('components', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('at_higher_levels', models.TextField(blank=True)),
                ('classes_using', models.ManyToManyField(blank=True, to='myapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('powers_description', models.TextField(blank=True)),
                ('dnd_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='myapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='Subrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('traits', models.TextField()),
                ('languages', models.ManyToManyField(blank=True, to='myapp.language')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('hit_points', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('alignment', models.CharField(max_length=50)),
                ('background', models.CharField(max_length=100)),
                ('proficiency_bonus', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('equipment', models.TextField()),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.class')),
                ('feats', models.ManyToManyField(blank=True, to='myapp.feat')),
                ('languages', models.ManyToManyField(blank=True, to='myapp.language')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.race')),
                ('subrace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subrace')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=20)),
                ('damage', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('weapon_type', models.CharField(blank=True, choices=[('simple', 'Simple'), ('martial', 'Martial')], max_length=10)),
                ('range_type', models.CharField(blank=True, choices=[('melee', 'Melee'), ('ranged', 'Ranged')], max_length=10)),
                ('properties', models.ManyToManyField(to='myapp.property')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rarity')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='weapon_proficiencies',
            field=models.ManyToManyField(to='myapp.weapon'),
        ),
    ]
