# Generated by Django 5.0.6 on 2024-05-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_armor_plus_dex_modifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='cost',
        ),
        migrations.AddField(
            model_name='armor',
            name='cost_in_gold',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
