# Generated by Django 5.0.6 on 2024-05-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_armor_cost_armor_cost_in_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='strength_requirement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
