# Generated by Django 5.0.6 on 2024-05-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_dice_remove_weapon_damage_weapon_number_of_dice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='ability_score_increases',
        ),
        migrations.RemoveField(
            model_name='race',
            name='racial_features',
        ),
        migrations.AddField(
            model_name='race',
            name='age',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='charisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='constitution',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='dexterity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='wisdom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='race',
            name='size',
            field=models.TextField(),
        ),
    ]
