# Generated by Django 5.0.6 on 2024-05-26 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myapp', '0007_remove_race_ability_score_increases_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProficiencyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField()),
                ('level_start', models.IntegerField()),
                ('level_end', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='language',
            name='famous_texts',
        ),
        migrations.RemoveField(
            model_name='language',
            name='learning_methods',
        ),
        migrations.RemoveField(
            model_name='language',
            name='magical_properties',
        ),
        migrations.RemoveField(
            model_name='language',
            name='script',
        ),
        migrations.RemoveField(
            model_name='language',
            name='speakers',
        ),
        migrations.RemoveField(
            model_name='language',
            name='special_characteristics',
        ),
        migrations.RemoveField(
            model_name='language',
            name='translation_difficulty',
        ),
        migrations.RemoveField(
            model_name='language',
            name='typical_settings',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='languages',
        ),
        migrations.AddField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='subrace',
            name='charisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subrace',
            name='constitution',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subrace',
            name='dexterity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subrace',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subrace',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.race'),
        ),
        migrations.AddField(
            model_name='subrace',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subrace',
            name='wisdom',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='race',
            name='traits',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='traits',
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('proficiency_bonuses', models.ManyToManyField(blank=True, to='myapp.proficiencybonus')),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('level', models.IntegerField(default=0)),
                ('proficiencies', models.ManyToManyField(blank=True, to='myapp.proficiency')),
                ('spells', models.ManyToManyField(blank=True, to='myapp.spell')),
            ],
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.AddField(
            model_name='race',
            name='traits',
            field=models.ManyToManyField(blank=True, to='myapp.trait'),
        ),
        migrations.AddField(
            model_name='subrace',
            name='traits',
            field=models.ManyToManyField(blank=True, to='myapp.trait'),
        ),
    ]
