# Generated by Django 5.0.6 on 2024-05-26 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_proficiencybonus_remove_language_famous_texts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proficiency',
            name='proficiency_bonuses',
        ),
        migrations.AddField(
            model_name='proficiency',
            name='proficiency_bonus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.proficiencybonus'),
        ),
    ]
