# Generated by Django 5.0.6 on 2024-05-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_proficiency_proficiency_bonuses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiency',
            name='proficiency_bonus',
            field=models.BooleanField(default=True),
        ),
    ]
