# Generated by Django 5.0.6 on 2024-05-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_proficiency_proficiency_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='saving_throw_proficiencies',
            field=models.ManyToManyField(to='myapp.savingthrow'),
        ),
    ]
