# Generated by Django 5.0.6 on 2024-05-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_class_saving_throw_proficiencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellLevelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('cantrips', models.IntegerField(blank=True, default=0)),
                ('spells_known', models.CharField(blank=True, default='', max_length=100)),
                ('spells_ready', models.CharField(blank=True, default='', max_length=100)),
                ('slots_level_1', models.IntegerField(default=0)),
                ('slots_level_2', models.IntegerField(default=0)),
                ('slots_level_3', models.IntegerField(default=0)),
                ('slots_level_4', models.IntegerField(default=0)),
                ('slots_level_5', models.IntegerField(default=0)),
                ('slots_level_6', models.IntegerField(default=0)),
                ('slots_level_7', models.IntegerField(default=0)),
                ('slots_level_8', models.IntegerField(default=0)),
                ('slots_level_9', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='powers_description',
        ),
        migrations.AddField(
            model_name='class',
            name='traits',
            field=models.ManyToManyField(blank=True, to='myapp.trait'),
        ),
        migrations.AlterField(
            model_name='class',
            name='armor_proficiencies',
            field=models.ManyToManyField(blank=True, to='myapp.armor'),
        ),
        migrations.AlterField(
            model_name='class',
            name='tool_proficiencies',
            field=models.ManyToManyField(blank=True, to='myapp.tool'),
        ),
        migrations.AlterField(
            model_name='class',
            name='weapon_proficiencies',
            field=models.ManyToManyField(blank=True, to='myapp.weapon'),
        ),
    ]
