# Generated by Django 5.0.6 on 2024-05-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_spelllevelinfo_remove_class_powers_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spelllevelinfo',
            name='slots_level_1',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='spelllevelinfo',
            name='slots_level_2',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='spelllevelinfo',
            name='slots_level_3',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='spelllevelinfo',
            name='slots_level_4',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='spelllevelinfo',
            name='slots_level_5',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='spelllevelinfo',
            name='slots_level_6',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='spelllevelinfo',
            name='slots_level_7',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='spelllevelinfo',
            name='slots_level_8',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='spelllevelinfo',
            name='slots_level_9',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
