# Generated by Django 5.0.6 on 2024-05-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_spelllevelinfo_slots_level_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spelllevelinfo',
            name='cantrips',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
