# Generated by Django 5.0.6 on 2024-05-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_spelllevelinfo_cantrips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spelllevelinfo',
            name='cantrips',
        ),
    ]
