# Generated by Django 5.0.6 on 2024-05-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_spelllevelinfo_cantrips'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('level_1', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_2', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_3', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_4', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_5', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_6', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_7', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_8', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_9', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_10', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_11', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_12', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_13', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_14', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_15', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_16', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_17', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_18', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_19', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
                ('level_20', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SpellLevelInfo',
        ),
    ]
