# Generated by Django 5.0.6 on 2024-05-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_spellslots_delete_spelllevelinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('simple', 'Simple'), ('martial', 'Martial')], max_length=20)),
                ('type', models.CharField(choices=[('melee', 'Melee'), ('ranged', 'Ranged')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='hit_die',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dice'),
        ),
        migrations.CreateModel(
            name='ArmorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('armors', models.ManyToManyField(related_name='groups', to='myapp.armor')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='armor_groups',
            field=models.ManyToManyField(blank=True, to='myapp.armorgroup'),
        ),
        migrations.AddField(
            model_name='class',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='myapp.equipment'),
        ),
        migrations.CreateModel(
            name='EquipmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('armors', models.ManyToManyField(blank=True, to='myapp.armor')),
                ('tools', models.ManyToManyField(blank=True, to='myapp.tool')),
                ('weapons', models.ManyToManyField(blank=True, to='myapp.weapon')),
                ('items', models.ManyToManyField(blank=True, to='myapp.item')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='myapp.equipmentoption'),
        ),
        migrations.CreateModel(
            name='WeaponGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('weapons', models.ManyToManyField(related_name='groups', to='myapp.weapon')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='weapon_groups',
            field=models.ManyToManyField(blank=True, to='myapp.weapongroup'),
        ),
    ]
