# Generated by Django 5.0.6 on 2024-05-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_equipment_item_weaponcategory_alter_class_hit_die_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
