# Generated by Django 5.0.6 on 2024-05-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_equipment_equipment_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='ArmorGroup',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='WeaponGroup',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='armors',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_options',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='weapons',
        ),
        migrations.AddField(
            model_name='equipment',
            name='ArmorGroup1',
            field=models.ManyToManyField(blank=True, related_name='equipments1', to='myapp.armorgroup'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ArmorGroup2',
            field=models.ManyToManyField(blank=True, related_name='equipments2', to='myapp.armorgroup'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ArmorGroup3',
            field=models.ManyToManyField(blank=True, related_name='equipments3', to='myapp.armorgroup'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='WeaponGroup1',
            field=models.ManyToManyField(blank=True, related_name='equipments1', to='myapp.weapongroup'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='WeaponGroup2',
            field=models.ManyToManyField(blank=True, related_name='equipments2', to='myapp.weapongroup'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='WeaponGroup3',
            field=models.ManyToManyField(blank=True, related_name='equipments3', to='myapp.weapongroup'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='armors1',
            field=models.ManyToManyField(blank=True, related_name='equipments1', to='myapp.armor'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='armors2',
            field=models.ManyToManyField(blank=True, related_name='equipments2', to='myapp.armor'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='armors3',
            field=models.ManyToManyField(blank=True, related_name='equipments3', to='myapp.armor'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_options1',
            field=models.ManyToManyField(blank=True, related_name='equipments1', to='myapp.equipmentoption'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_options2',
            field=models.ManyToManyField(blank=True, related_name='equipments2', to='myapp.equipmentoption'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_options3',
            field=models.ManyToManyField(blank=True, related_name='equipments3', to='myapp.equipmentoption'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tools1',
            field=models.ManyToManyField(blank=True, related_name='equipments1', to='myapp.tool'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tools2',
            field=models.ManyToManyField(blank=True, related_name='equipments2', to='myapp.tool'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tools3',
            field=models.ManyToManyField(blank=True, related_name='equipments3', to='myapp.tool'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weapons1',
            field=models.ManyToManyField(blank=True, related_name='equipments1', to='myapp.weapon'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weapons2',
            field=models.ManyToManyField(blank=True, related_name='equipments2', to='myapp.weapon'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weapons3',
            field=models.ManyToManyField(blank=True, related_name='equipments3', to='myapp.weapon'),
        ),
    ]
