# Generated by Django 5.0.6 on 2024-05-28 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_equipment_armorgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='ArmorGroup1',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ArmorGroup2',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ArmorGroup3',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='WeaponGroup1',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='WeaponGroup2',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='WeaponGroup3',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='armors1',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='armors2',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='armors3',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_options1',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_options2',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_options3',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='tools1',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='tools2',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='tools3',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='weapons1',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='weapons2',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='weapons3',
        ),
        migrations.AddField(
            model_name='equipment',
            name='armor1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments1', to='myapp.armor'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='armor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments2', to='myapp.armor'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='armor3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments3', to='myapp.armor'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='armor_group1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments1', to='myapp.armorgroup'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='armor_group2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments2', to='myapp.armorgroup'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='armor_group3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments3', to='myapp.armorgroup'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_option1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments1', to='myapp.equipmentoption'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_option2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments2', to='myapp.equipmentoption'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_option3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments3', to='myapp.equipmentoption'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tool1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments1', to='myapp.tool'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tool2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments2', to='myapp.tool'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tool3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments3', to='myapp.tool'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weapon1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments1', to='myapp.weapon'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weapon2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments2', to='myapp.weapon'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weapon3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments3', to='myapp.weapon'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weapon_group1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments1', to='myapp.weapongroup'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weapon_group2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments2', to='myapp.weapongroup'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weapon_group3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments3', to='myapp.weapongroup'),
        ),
    ]
