# Generated by Django 5.0.6 on 2024-05-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_equipment_armorgroup1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='hit_points_at_first_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='hit_points_at_higher_levels',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
