# Generated by Django 5.0.6 on 2024-05-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_class_hit_points_at_first_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subclass',
            name='powers_description',
        ),
        migrations.AddField(
            model_name='subclass',
            name='traits',
            field=models.ManyToManyField(blank=True, to='myapp.trait'),
        ),
    ]
