# Generated by Django 5.0.6 on 2024-06-08 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_castingtime_components_duration_range_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='damage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.damagetype'),
        ),
        migrations.AddField(
            model_name='spell',
            name='dice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.dice'),
        ),
        migrations.AddField(
            model_name='spell',
            name='dice_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
