from django.contrib import admin
from .models import Rarity, Character, Equipment, SpellSlots, Dice, DamageType, Armor, Property, Weapon, Tool, AbilityScore, Skill, SavingThrow, Class, Subclass, Race, Subrace, Spell, Language, Feat, ProficiencyBonus, Proficiency, Trait, WeaponCategory, WeaponGroup, ArmorGroup, Item, EquipmentOption, User

admin.site.register(Character)
admin.site.register(Rarity)
admin.site.register(Dice)
admin.site.register(DamageType)
admin.site.register(Armor)
admin.site.register(Property)
admin.site.register(Weapon)
admin.site.register(Tool)
admin.site.register(AbilityScore)
admin.site.register(Skill)
admin.site.register(SavingThrow)
admin.site.register(Class)
admin.site.register(Subclass)
admin.site.register(Race)
admin.site.register(Subrace)
admin.site.register(Spell)
admin.site.register(Language)
admin.site.register(Feat)
admin.site.register(ProficiencyBonus)
admin.site.register(Proficiency)
admin.site.register(Trait)
admin.site.register(SpellSlots)
admin.site.register(Equipment)
admin.site.register(WeaponCategory)
admin.site.register(WeaponGroup)
admin.site.register(ArmorGroup)
admin.site.register(Item)
admin.site.register(EquipmentOption)
admin.site.register(User)
